### ISSUE TITLE
Question/Suggest about your Menu

### ISSUE THREAD

**Issue by Greg-Obleshchuk** [raj03kumar/mega-navbar#1]
Hi ,
I like your menu from what I have seen it works really well.  My issue is one of cross compatibility.  Looking at the styles in your CSS it seems to me that these would conflict with Bootstrap or other libraries (ie .navbar and .btn ) One way around this is to prefix your classes with say your project name (ie mb-navbar and mb-btn ) and try to say away from object classes like ul and a .
Have you had any trouble with using this menu with bootstrap or other libries? 
cheers
Greg

**Comment by raj03kumar** [comment]
Hii Greg, I can understand your concern. You can change the classname accordingly. I took the simple name so that it is easy to figure out. You can change it according to your preferences.
